GEMINI_API_KEY = "AIzaSyDZLOoZ1qXUx15dTYqwTJ1eVYdL0vfxqto"
AZURE_ENDPOINT = "https://motor-extrator-v2-elizandro.cognitiveservices.azure.com/"
AZURE_KEY = "DdNaOKYLMcExu0zx4JvsSS90sl4ITd0mwSR4VOnQFfk7vSVRgofvJQQJ99CEACYeBjFXJ3w3AAALACOGF2Jyi"